<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VSP.Core\VSP.Core.csproj" />
    <ProjectReference Include="..\VSP.Domain\VSP.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Settings\" />
    <Folder Include="SDK\" />
    <Folder Include="ONVIF\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
  </ItemGroup>

</Project>
