<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VSP.Core\VSP.Core.csproj" />
    <ProjectReference Include="..\VSP.Domain\VSP.Domain.csproj" />
    <ProjectReference Include="..\VSP.Infrastructure\VSP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Plugins\" />
  </ItemGroup>

</Project>
