[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..")).Path
$generator = Join-Path $PSScriptRoot "generate-artifact-intake-validator.ps1"
$tempRoot = Join-Path ([IO.Path]::GetTempPath()) ("ai02-a2-gen1-generator-test-" + [Guid]::NewGuid().ToString("N"))
$script:passed = 0
$script:failed = 0

function Pass([string] $Name) { $script:passed++; Write-Output "PASS: $Name" }
function Fail([string] $Name, [string] $Message) { $script:failed++; Write-Output "FAIL: $Name -- $Message" }
function Assert-True([bool] $Condition, [string] $Name) { if ($Condition) { Pass $Name } else { Fail $Name "assertion was false" } }
function Read-Json([string] $Path) { Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json -AsHashtable -Depth 100 }
function Write-Json($Value, [string] $Path) {
    $json = ($Value | ConvertTo-Json -Depth 100).Replace("`r`n", "`n").Replace("`r", "`n") + "`n"
    [IO.File]::WriteAllText($Path, $json, [Text.UTF8Encoding]::new($false))
}

function Invoke-Generation([string] $OutputDirectory, [hashtable] $Extra = @{}) {
    $arguments = @{ OutputDirectory = $OutputDirectory }
    foreach ($key in $Extra.Keys) { $arguments[$key] = $Extra[$key] }
    return (& $generator @arguments | Out-String).Trim() | ConvertFrom-Json
}

function Invoke-InvalidInputCase([string] $Name, [scriptblock] $Mutation, [string] $InputName = "PolicyPath") {
    $caseRoot = Join-Path $tempRoot ("invalid-" + $Name)
    New-Item -ItemType Directory -Force -Path $caseRoot | Out-Null
    $source = switch ($InputName) {
        "PolicyPath" { Join-Path $repoRoot "AI/Orchestrator/Policy/artifact-intake-policy.json" }
        "PolicySchemaPath" { Join-Path $repoRoot "AI/Orchestrator/Policy/artifact-intake-policy.schema.json" }
        "RequestSchemaPath" { Join-Path $repoRoot "AI/Orchestrator/Templates/artifact-intake-request.schema.json" }
        default { throw "unknown input" }
    }
    $candidate = Read-Json $source
    & $Mutation $candidate
    $candidatePath = Join-Path $caseRoot "candidate.json"
    Write-Json $candidate $candidatePath
    $output = Join-Path $caseRoot "out"
    $failed = $false
    try {
        $extra = @{ $InputName = $candidatePath }
        Invoke-Generation -OutputDirectory $output -Extra $extra | Out-Null
    } catch {
        $failed = $true
    }
    Assert-True $failed "invalid input rejected: $Name"
    Assert-True (-not (Test-Path -LiteralPath (Join-Path $output "tools/orchestrator/artifact-intake-contract.ps1"))) "invalid input leaves no usable production output: $Name"
}

try {
    New-Item -ItemType Directory -Force -Path $tempRoot | Out-Null
    $run1 = Join-Path $tempRoot "run1"
    $run2 = Join-Path $tempRoot "run2"
    $e1 = Invoke-Generation $run1
    $e2 = Invoke-Generation $run2
    $out1 = Join-Path $run1 "tools/orchestrator/artifact-intake-contract.ps1"
    $out2 = Join-Path $run2 "tools/orchestrator/artifact-intake-contract.ps1"

    Assert-True (Test-Path -LiteralPath $out1 -PathType Leaf) "one staged production file generated"
    Assert-True (@(Get-ChildItem -LiteralPath $run1 -Recurse -File).Count -eq 1) "staging output contains exactly one file"
    Assert-True ($e1.generatedSha256 -ceq $e2.generatedSha256) "deterministic generated SHA"
    Assert-True ($e1.generatedByteSize -eq $e2.generatedByteSize) "deterministic generated size"
    Assert-True ([Convert]::ToBase64String([IO.File]::ReadAllBytes($out1)) -ceq [Convert]::ToBase64String([IO.File]::ReadAllBytes($out2))) "deterministic generated bytes"

    $bytes = [IO.File]::ReadAllBytes($out1)
    $text = [Text.Encoding]::UTF8.GetString($bytes)
    Assert-True (-not ($bytes.Length -ge 3 -and $bytes[0] -eq 0xef -and $bytes[1] -eq 0xbb -and $bytes[2] -eq 0xbf)) "generated output is UTF-8 without BOM"
    Assert-True (-not $text.Contains("`r")) "generated output is LF-only"
    Assert-True (-not ($text -match "(?i)Get-Date|New-Guid|Invoke-WebRequest|Invoke-RestMethod|gh api|git push|repository-transport|GITHUB_TOKEN|VSP_AI_APP_PRIVATE_KEY")) "generated runtime has no prohibited external/write/credential calls"
    Assert-True ($text.Contains("PolicyProjectionJson")) "generated output embeds generated normative policy projection table"

    $tokens = $null
    $errors = $null
    [Management.Automation.Language.Parser]::ParseFile($out1, [ref]$tokens, [ref]$errors) | Out-Null
    Assert-True ($errors.Count -eq 0) "generated output parses as PowerShell"

    $policy = Read-Json (Join-Path $repoRoot "AI/Orchestrator/Policy/artifact-intake-policy.json")
    $request = Read-Json (Join-Path $repoRoot "AI/Orchestrator/Templates/artifact-intake-request.template.json")
    $projection = [ordered]@{
        repositoryPath = $policy.repositoryPath
        limits = $policy.limits
        replay = $policy.replay
        staleBase = $policy.staleBase
        credentialInvariants = $policy.credentialInvariants
        transport = $policy.transport
    }
    Assert-True ((($request.policy | ConvertTo-Json -Depth 100 -Compress) -ceq ($projection | ConvertTo-Json -Depth 100 -Compress))) "canonical six-section projection is the schema-approved policy"

    Invoke-InvalidInputCase "policy numeric ceiling drift" { param($p) $p.limits.maxChangedFiles = 201 }
    Invoke-InvalidInputCase "policy credential drift" { param($p) $p.credentialInvariants.trustedIntakeRepositoryWriteAuthority = $true }
    Invoke-InvalidInputCase "policy unknown top-level field" { param($p) $p.extra = $true }
    Invoke-InvalidInputCase "unsupported policy schema dialect" { param($s) $s['$schema'] = "https://json-schema.org/draft/2019-09/schema" } "PolicySchemaPath"
    Invoke-InvalidInputCase "unsupported request schema dialect" { param($s) $s['$schema'] = "https://json-schema.org/draft/2019-09/schema" } "RequestSchemaPath"

    $duplicatePath = Join-Path $tempRoot "duplicate.json"
    [IO.File]::WriteAllText($duplicatePath, '{"schemaVersion":"1.0","schemaVersion":"1.0"}', [Text.UTF8Encoding]::new($false))
    $duplicateFailed = $false
    try { Invoke-Generation (Join-Path $tempRoot "duplicate-out") @{ PolicyPath = $duplicatePath } | Out-Null } catch { $duplicateFailed = $true }
    Assert-True $duplicateFailed "duplicate JSON properties rejected"

    $bomPath = Join-Path $tempRoot "bom.json"
    [IO.File]::WriteAllBytes($bomPath, [byte[]](0xef,0xbb,0xbf) + [Text.Encoding]::UTF8.GetBytes('{"schemaVersion":"1.0"}'))
    $bomFailed = $false
    try { Invoke-Generation (Join-Path $tempRoot "bom-out") @{ PolicyPath = $bomPath } | Out-Null } catch { $bomFailed = $true }
    Assert-True $bomFailed "BOM input rejected"
}
finally {
    Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Output "A2-GEN1 generator focused tests: $script:passed passed, $script:failed failed"
if ($script:failed -ne 0) { exit 1 }
