<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="VSP.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VSP.Core\VSP.Core.csproj" />
    <ProjectReference Include="..\VSP.Device\VSP.Device.csproj" />
    <ProjectReference Include="..\VSP.Infrastructure\VSP.Infrastructure.csproj" />
    <ProjectReference Include="..\VSP.Player\VSP.Player.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="Themes\" />
    <Folder Include="Views\Dashboard\" />
    <Folder Include="Views\DeviceCenter\Components\" />
    <Folder Include="Views\DeviceCenter\Dialogs\" />
    <Folder Include="Views\LiveView\" />
    <Folder Include="Views\Shared\" />
    <Folder Include="Views\Settings\" />
    <Folder Include="Views\Playback\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

</Project>
